// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiSEP7.Data;

#nullable disable

namespace WebApiSEP7.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("WebApiSEP7.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("WebApiSEP7.Models.MedicalInformation", b =>
                {
                    b.Property<int>("MedicalInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("BMI")
                        .HasColumnType("REAL");

                    b.Property<int>("BloodGlucoseLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChestPainType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cholesterol")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Diabetes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseAngina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FastingBS")
                        .HasColumnType("INTEGER");

                    b.Property<float>("HbA1cLevel")
                        .HasColumnType("REAL");

                    b.Property<int>("HeartDisease")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hypertension")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHR")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Oldpeak")
                        .HasColumnType("REAL");

                    b.Property<int>("RestingBP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestingECG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestingECG_LVH")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestingECG_Normal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestingECG_ST")
                        .HasColumnType("INTEGER");

                    b.Property<int>("STSlope")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SmokingHistory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MedicalInformationId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("MedicalInformations");
                });

            modelBuilder.Entity("WebApiSEP7.Models.PersonalInformation", b =>
                {
                    b.Property<int>("PersonalInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConsumesAlcohol")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Height")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsPregnant")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Smokes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("PersonalInformationId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PersonalInformations");
                });

            modelBuilder.Entity("WebApiSEP7.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ServiceId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("WebApiSEP7.Models.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("SubscriptionId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("WebApiSEP7.Models.SubscriptionCategory", b =>
                {
                    b.Property<int>("SubscriptionCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SubscriptionCategoryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionCategories");
                });

            modelBuilder.Entity("WebApiSEP7.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApiSEP7.Models.MedicalInformation", b =>
                {
                    b.HasOne("WebApiSEP7.Models.User", "User")
                        .WithOne("MedicalInformation")
                        .HasForeignKey("WebApiSEP7.Models.MedicalInformation", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApiSEP7.Models.PersonalInformation", b =>
                {
                    b.HasOne("WebApiSEP7.Models.User", "User")
                        .WithOne("PersonalInformation")
                        .HasForeignKey("WebApiSEP7.Models.PersonalInformation", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApiSEP7.Models.Service", b =>
                {
                    b.HasOne("WebApiSEP7.Models.Category", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebApiSEP7.Models.SubscriptionCategory", b =>
                {
                    b.HasOne("WebApiSEP7.Models.Category", "Category")
                        .WithMany("SubscriptionCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiSEP7.Models.Subscription", "Subscription")
                        .WithMany("SubscriptionCategories")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("WebApiSEP7.Models.User", b =>
                {
                    b.HasOne("WebApiSEP7.Models.Subscription", "Subscription")
                        .WithMany("Users")
                        .HasForeignKey("SubscriptionId");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("WebApiSEP7.Models.Category", b =>
                {
                    b.Navigation("Services");

                    b.Navigation("SubscriptionCategories");
                });

            modelBuilder.Entity("WebApiSEP7.Models.Subscription", b =>
                {
                    b.Navigation("SubscriptionCategories");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebApiSEP7.Models.User", b =>
                {
                    b.Navigation("MedicalInformation");

                    b.Navigation("PersonalInformation");
                });
#pragma warning restore 612, 618
        }
    }
}
